server:
  port: 8080
spring:
  application:
    name: my-spring
  datasource:
     url: jdbc:hive2://192.168.99.100:10000/test
     username: root
     password: 123456
     driver-class-name: org.apache.hive.jdbc.HiveDriver
     type: com.alibaba.druid.pool.DruidDataSource
     initialSize: 5
     minIdle: 5
     maxActive: 20
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     testWhileIdle: false
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true

logging:
  config: classpath:log4j2.xml

corn-fix-time: '0/10 * * * * ? '

# 上传文件总的最大值
spring.servlet.multipart.max-request-size: 10MB
# 单个文件的最大值
spring.servlet.multipart.max-file-size: 10MB


